catalog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from catalog import views
from catalog.apps import CatalogConfig
from catalog.views import catalog_list, ContactsPageView, CategoryListView, \
    ProductListView, ProductByCategoryListView, ItemDetailView, ProductCreateView, ProductUpdateView, BlogCreateView, \
    BlogListView, BlogDetailView, \
    BlogUpdateView, BlogDeleteView, toggle_activity, ProductDeleteView, CategoryCreateView, CategoryUpdateView, \
    CategoryDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', catalog_list, name='catalog_list'),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('products/', ProductListView.as_view(), name='products'),
    path('contacts/', ContactsPageView.as_view(), name='contacts'),
    path('<int:pk>/products_by_category/', ProductByCategoryListView.as_view(), name='products_by_category'),
    #path('item/<int:pk>', ItemDetailView.as_view(), name='item'),
    path('item/<int:pk>/', cache_page(60)(views.ItemDetailView.as_view()), name='item'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view_blog'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),
    path('published/<int:pk>/', toggle_activity, name='toggle_activity'),
   # path('products_by_category/create/', ProductCreateView.as_view(), name='create_product'),
    path('products_by_category/create/', never_cache(views.ProductCreateView.as_view()), name='create_product'),
    #path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    path('products/<int:pk>/update/', never_cache(views.ProductUpdateView.as_view()), name='update_product'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='delete_product'),
    path('categories/create/', CategoryCreateView.as_view(), name='create_category'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='update_category'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='delete_category'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('users/', include('users.urls', namespace='users')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, UserConfirmEmailView, EmailConfirmationSentView, EmailConfirmView, \
    EmailConfirmationFailedView, generate_new_password, UserForgotPasswordView, UserPasswordResetConfirmView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:token>/', UserConfirmEmailView.as_view(), name='email_verified'),
    path('email-confirmed/', EmailConfirmView.as_view(), name='email_verified'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('password_reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),


]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)

    country = models.CharField(verbose_name='страна', **NULLABLE)

    token = models.CharField(max_length=200, verbose_name='токен', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='время создания токена', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm, SetPasswordForm

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin,UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({"placeholder": 'Введите свой email'})
        self.fields['first_name'].widget.attrs.update({"placeholder": 'Ваше имя'})
        self.fields["last_name"].widget.attrs.update({"placeholder": 'Ваша фамилия'})
        self.fields["avatar"].widget.attrs.update({"placeholder": 'Ваша автарка'})
        self.fields['password'].widget = forms.HiddenInput()


class UserForgotPasswordForm(StyleFormMixin, PasswordResetForm):
    """Запрос на восстановление пароля"""

    def __init__(self, *args, **kwargs):
        """Обновление стилей формы"""
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class UserSetNewPasswordForm(StyleFormMixin, SetPasswordForm):
    """Изменение пароля пользователя после подтверждения"""

    def __init__(self, *args, **kwargs):
        """Обновление стилей формы"""
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })

users/views.py
import random

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView

from users.forms import UserRegisterForm, UserProfileForm, UserForgotPasswordForm, UserSetNewPasswordForm
from users.models import User
from users.service import send_new_password


# Create your views here.
class RegisterView(LoginRequiredMixin, CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.token = default_token_generator.make_token(user)
        activation_url = reverse_lazy(
            'users:email_verified', kwargs={'token': user.token}
        )
        send_mail(
            subject='Подтверждение почты',
            message=f'Для подтверждения регистрации перейдите по ссылке: http://localhost:8000/{activation_url}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
            fail_silently=False
        )
        user.save()
        return redirect('users:email_confirmation_sent')


class UserConfirmEmailView(LoginRequiredMixin, View):
    def get(self, request, token):
        try:
            user = User.objects.get(token=token)
        except User.DoesNotExist:
            return redirect('users:email_confirmation_failed')

        user.is_active = True
        user.token = None
        user.save()
        return redirect('users:login')


class EmailConfirmationSentView(LoginRequiredMixin, TemplateView):
    template_name = 'users/email_confirmation_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо активации отправлено'
        return context


class EmailConfirmView(LoginRequiredMixin, TemplateView):
    template_name = 'users/email_verified.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес активирован'
        return context


class EmailConfirmationFailedView(LoginRequiredMixin,TemplateView):
    """Ошибка подтверждения по электронной почте"""
    template_name = 'users/email_confirmation_failed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес не активирован'
        return context


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')
    template_name = 'users/user_form.html'

    def get_object(self, queryset=None):
        """метод который забирает - pk, его не надо указывать в урлах"""
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Страница пользователя: {self.object.email}'
        return context


@login_required
def generate_new_password(request):
    """Сброс пароля зарегистрированного пользователя в профиле"""
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(13)])
    # send_mail(
    #     subject='Вы сменили пароль',
    #     message=f'Ваш новый пароль: {new_password}',
    #     from_email=settings.EMAIL_HOST_USER,
    #     recipient_list=[request.user.email]
    # )
    request.user.set_password(new_password)
    request.user.save()
    send_new_password(request.user.email, new_password)
    return redirect(reverse('catalog:catalog_list'))


class UserForgotPasswordView(LoginRequiredMixin, SuccessMessageMixin, PasswordResetView):
    """Представление по сбросу пароля по почте"""
    form_class = UserForgotPasswordForm
    template_name = 'users/user_password_reset.html'
    success_url = reverse_lazy('catalog:index')
    success_message = 'Письмо с инструкцией по восстановлению пароля отправлена на ваш email'
    subject_template_name = 'users/email/password_subject_reset_mail.txt'
    email_template_name = 'users/email/password_reset_mail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Запрос на восстановление пароля'
        return context


class UserPasswordResetConfirmView(LoginRequiredMixin,
                                   SuccessMessageMixin, PasswordResetConfirmView):
    """Представление установки нового пароля"""
    form_class = UserSetNewPasswordForm
    template_name = 'users/user_password_set_new.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Пароль успешно изменен. Можете авторизоваться на сайте.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Установить новый пароль'
        return context

    def get_object(self):
        return self.request.user

users/templates/users/email_code.html
{% extends 'catalog/base.html' %}
{% block card %}

    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    Вам на почту было отправлено письмо с кодом.
                    <br>
                    <form>
                        <label class="name">Ваш код подтверждения:</label>
                        <input type="text" id="code">
                    </form>
                    <input type="submit" class="btn btn-success" value="Подтвердить">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'catalog:blog_list' %}" role="button">Отмена
                    &raquo;</a>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/email_confirmation_failed.html
{% extends 'catalog/base.html' %}
{% block card %}

<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Ошибка подтверждения по электронной почте</h4>
    <p>Ссылка для подтверждения по электронной почте недействительна или срок ее действия истек. Пожалуйста, зарегистрируйтесь снова.</p>
</div>

{% endblock %}

users/templates/users/email_confirmation_sent.html
{% extends 'catalog/base.html' %}
{% block card %}

<div class="alert alert-info" role="alert">
    <h4 class="alert-heading">Письмо-подтверждение отправлено!</h4>
    <p>
        На ваш адрес электронной почты было отправлено письмо с подтверждением.
        Пожалуйста, проверьте свою электронную почту и нажмите на ссылку подтверждения, чтобы завершить регистрацию.
        Если письмо не пришло, проверьте папку спам.
    </p>
</div>

{% endblock %}

users/templates/users/email_verified.html
{% extends 'catalog/base.html' %}
{% block card %}

<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Электронная почта подтверждена</h4>
    <p>Ваш адрес электронной почты успешно подтвержден. Спасибо за регистрацию! Можете войти на сайт</p>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}


{% block content %}
 <div class="col">
        <form class="row" method="post">
          <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                  <div class="card-header">
                    <h3 class="card-title">
                      Вход
                    </h3>
                  </div>
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">

                          Войти

                        </button>

                    </div>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'catalog/base.html' %}

{% block card %}

    <div class="col-3"></div>
    <div class="col-6">
        <div class="uk-card">
            <div class="uk-card-header"></div>
            <div class="uk-card-body">
                <form method="POST" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="name">Имя</label>
                        <input type="text" name="email" class="form-control" id="email" placeholder="Почта" required>
                    </div>

                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </form>
            </div>

        </div>
    </div>

{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}


{% block content %}
 <div class="col">
        <form class="row" method="post">
          <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                  <div class="card-header">
                    <h3 class="card-title">
                      Регистрация
                    </h3>
                  </div>
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">

                          Зарегистрироваться

                        </button>

                    </div>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}


{% block content %}
 <div class="col">
        <form class="row" method="post" enctype="multipart/form-data">
          <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                  <div class="card-header">
                    <h3 class="card-title">
                      Профиль
                    </h3>
                  </div>
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">

                          Сохранить

                        </button>

                    </div>
                    <div class="card-footer">
                        <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
                    </div>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

users/templates/users/user_password_reset.html
{% extends 'catalog/base.html' %}
{% block card %}

    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Запрос на восстановление пароля на сайте</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark mt-2">Восстановить пароль</button>
            </form>
        </div>
    </div>

{% endblock %}

users/templates/users/user_password_set_new.html
{% extends 'catalog/base.html' %}
{% block card %}

<div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Установить новый пароль</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark mt-2">Подтвердить</button>
            </form>
        </div>
    </div>

{% endblock %}