catalog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from catalog import views
from catalog.apps import CatalogConfig
from catalog.views import catalog_list, ContactsPageView, CategoryListView, \
    ProductListView, ProductByCategoryListView, ItemDetailView, ProductCreateView, ProductUpdateView, BlogCreateView, \
    BlogListView, BlogDetailView, \
    BlogUpdateView, BlogDeleteView, toggle_activity, ProductDeleteView, CategoryCreateView, CategoryUpdateView, \
    CategoryDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', catalog_list, name='catalog_list'),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('products/', ProductListView.as_view(), name='products'),
    path('contacts/', ContactsPageView.as_view(), name='contacts'),
    path('<int:pk>/products_by_category/', ProductByCategoryListView.as_view(), name='products_by_category'),
    #path('item/<int:pk>', ItemDetailView.as_view(), name='item'),
    path('item/<int:pk>/', cache_page(60)(views.ItemDetailView.as_view()), name='item'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view_blog'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),
    path('published/<int:pk>/', toggle_activity, name='toggle_activity'),
   # path('products_by_category/create/', ProductCreateView.as_view(), name='create_product'),
    path('products_by_category/create/', never_cache(views.ProductCreateView.as_view()), name='create_product'),
    #path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    path('products/<int:pk>/update/', never_cache(views.ProductUpdateView.as_view()), name='update_product'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='delete_product'),
    path('categories/create/', CategoryCreateView.as_view(), name='create_category'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='update_category'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='delete_category'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('users/', include('users.urls', namespace='users')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, UserConfirmEmailView, EmailConfirmationSentView, EmailConfirmView, \
    EmailConfirmationFailedView, generate_new_password, UserForgotPasswordView, UserPasswordResetConfirmView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:token>/', UserConfirmEmailView.as_view(), name='email_verified'),
    path('email-confirmed/', EmailConfirmView.as_view(), name='email_verified'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('password_reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),


]

catalog/models.py
from django.db import models
from django.urls import reverse


from users.models import User

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    """Модель Category"""
    name = models.CharField(max_length=200, verbose_name='Наименование')
    description = models.TextField(max_length=500, verbose_name='Описание')


    def __str__(self):
        return f'{self.name} ({self.description})'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


# Create your models here.
class Product(models.Model):
    """Модель Product"""
    name = models.CharField(max_length=200, verbose_name='Наименование')
    description = models.TextField(max_length=500, verbose_name='Описание')
    photo = models.ImageField(upload_to='products/', **NULLABLE, verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, **NULLABLE, verbose_name='Категория')
    price = models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')
    date_of_creation = models.DateField(verbose_name='Дата создания')
    date_last_modified = models.DateField(**NULLABLE, verbose_name='Дата последнего изменения')

    views_count = models.IntegerField(default=0, verbose_name='Просмотры')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)

    owner = models.ForeignKey(User, on_delete=models.PROTECT, **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    class Meta:
        permissions = [
            (
                "set_published_status",
                "Can publish card"
            ),
            (
                "set_description",
                "Can description product",
            ),
            (
                "set_category",
                "Can category product"
            )
        ]

    def __str__(self):
        return f'{self.name} ({self.category}) ({self.price})'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

class Blog(models.Model):
    '''Модель блог'''
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=200, verbose_name='slug')
    content = models.TextField(**NULLABLE, verbose_name='Cодержимое')
    preview = models.ImageField(upload_to='previews/', verbose_name='Изображение')
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='Kоличество просмотров')

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        """Slug"""
        return reverse('blog_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'blog'
        verbose_name_plural = 'blogs'

class Version(models.Model):
    '''Модель версии продукта'''
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, verbose_name='Продукт')
    version_number = models.CharField(max_length=50, verbose_name='Номер версии')
    version_name = models.CharField(max_length=250, verbose_name='Название версии')
    is_active = models.BooleanField(default=True, verbose_name='Активная версия')

    def __str__(self):
        return f'{self.product} ({self.version_number})'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core import cache
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from catalog.forms import ProductForm, VersionForm, CategoryForm
from catalog.models import Category, Product, Blog, Version
from catalog.service import get_categories_cache


# Create your views here.


def catalog_list(request):
    """Контроллер страницы catalog_list"""
    # if settings.CACHE_ENABLED:
    #     key = 'category_list'
    #     category_list = cache.get(key)
    #     if category_list is None:
    #         category_list = Category.objects.all()
    #         cache.set(key, category_list)
    # else:
    #     category_list = Category.objects.all()

    context = {
        'object_list': get_categories_cache(),
        'title': 'Главная'
    }
    return render(request, 'catalog\catalog_list.html', context)


# def categories(request):
#     """Контроллер страницы categories"""
#     context = {
#         'object_list': Category.objects.all(),
#         'title': 'Категории'
#     }
#     return render(request, 'catalog\category_list.html', context)

class CategoryListView(ListView):
    model = Category
    extra_context = {
        'title': 'Категории'
    }


# def contacts(request):
#     """Контроллер страницы contacts"""
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         phone = request.POST.get('phone')
#         message = request.POST.get('message')
#         print(f"Имя: {name}\nТелефон: {phone}\nСообщение: {message}\n")
#     return render(request, 'catalog/contacts.html')

class ContactsPageView(TemplateView):
    template_name = 'catalog/contacts.html'
    extra_context = {'title': 'Контакты'}


# def products(request):
#     """Контроллер страницы products"""
#     context = {
#         'object_list': Product.objects.all(),
#         'title': 'Продукты'
#     }
#     return render(request, 'catalog\products.html', context)

class ProductListView(ListView):
    model = Product
    extra_context = {
        'title': 'Продукты'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.prefetch_related('version_set')
        return queryset


# def products_by_category(request, pk):
#     """Контроллер страницы products_by_category"""
#     category_item = Category.objects.get(pk=pk)
#     context = {
#         'object_list': Product.objects.filter(category_id=category_item.pk),
#         'title': f'Продукты {category_item.name}'
#
#     }
#     return render(request, 'catalog\products_by_category.html', context)


class ProductByCategoryListView(ListView):
    model = Product
    extra_context = {
        'title': 'Продукты'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['categoty_pk'] = category_item.pk
        context_data['title'] = f'Продукты {category_item.name}'
        return context_data


# def item(request, pk):
#     product_item = Product.objects.get(pk=pk)
#     context = {
#         'object': product_item,
#         'title': product_item.name
#     }
#     return render(request, 'catalog/item_detail.html', context)

class ItemDetailView(DetailView):
    model = Product
    extra_context = {
        'title': 'Продукты'
    }
    template_name = 'catalog/item_detail.html'

    def get_object(self, queryset=None):
        self.object = super().get_object()
        self.object.views_count += 1
        self.object.save()
        return self.object


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products')
    template_name = 'catalog/product_form.html'

    def test_func(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST)
        else:
            context_data['formset'] = VersionFormset()

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        if self.request.user.is_authenticated:
            self.object.owner = self.request.user
            self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products')
    template_name = 'catalog/product_form.html'

    def test_func(self):
        return self.request.user.is_staff or self.get_object().owner == self.request.user

    # def get_object(self, queryset=None):
    #     self.object = super().get_object(queryset)
    #     if self.object.owner != self.request.user:
    #         raise Http404
    #     return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST)
        else:
            context_data['formset'] = VersionFormset()

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        if self.request.user.is_authenticated:
            self.object.owner = self.request.user
            self.object.save()

        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:products')

    def test_func(self):
        return self.request.user.is_superuser or self.get_object().owner == self.request.user

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('catalog:categories')
    template_name = 'catalog/category_form.html'


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('catalog:categories')
    template_name = 'catalog/category_form.html'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('catalog:categories')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content',)
    success_url = reverse_lazy('catalog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'content',)

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object

    # success_url = reverse_lazy('catalog:blog_detail')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:view_blog', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog
    fields = ('title', 'content', 'is_published')

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blog_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


def toggle_activity(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.is_published:
        blog_item.is_published = False
    else:

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}


{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить запись "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-success">Подтвердить</button>
                            <a href="{% url 'catalog:blog_list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Блог {{ object.title }} ({{object.slug}})
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.content}}
                    </p>
                </div>

                <div class="card-footer">
                    Просмотры: {{ object.views_count }}
                    Опубликован: {{object.is_published}}
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<h1>Блог</h1>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_blog' %}">Добавить блог</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {{ object.title }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'catalog:view_blog' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Просмотр</a>
                    <a href="{% url 'catalog:edit_blog' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    <a href="{% url 'catalog:delete_blog' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Удалить</a>
                    {% if object.is_published %}
                     <a href="{% url 'catalog:toggle_activity' object.pk %}" type="button"
                       class="btn btn-warning">Заблокировать</a>
                    {% else %}
                     <a href="{% url 'catalog:toggle_activity' object.pk %}" type="button"
                       class="btn btn-success">Активировать</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/catalog_list.html
{% extends 'catalog/base.html' %}
{% load my_templatetags %}

{% block content%}
{% if user.is_authenticated %}
    <div class="col-12 pb-md-4">

        <a class="btn btn-primary" href="{%url 'catalog:create_product'%}">Добавить продукт</a>

    </div>
{% endif %}
<h1>Каталог SuperMag</h1>
 {% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name}}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li> {{ object.description}}</li>
                        </ul>
                        <a href="{% url 'catalog:products_by_category' object.pk %}">
                        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Просмотреть товары</button>
                        </a>
                    </div>
                </div>
            </div>
          {% endfor %}

{% endblock %}

catalog/templates/catalog/category_confirm_delete.html
{% extends 'catalog/base.html' %}


{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить запись "{{ object.name }}"?</p>
                            <button type="submit" class="btn btn-success">Подтвердить</button>
                            <a href="{% url 'catalog:categories' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/category_form.html
{% extends 'catalog/base.html' %}


{% block content %}
 <div class="col">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Cоздать
                                {% endif %}
                        </button>

                    </div>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content%}
<h1>Категории</h1>

{% if user.is_authenticated %}

    <div class="col-12 pb-md-4">

        <a class="btn btn-primary" href="{%url 'catalog:create_category'%}">Добавить категорию</a>

    </div>
{% endif %}

{% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name}}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li> {{ object.description}}</li>
                        </ul>
                    </div>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:products_by_category' object.pk %}">Перейти в Каталог</a>
                </div>

            </div>
          {% endfor %}

{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<h1>Контакты</h1>
<br>
<form method="post">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Имя">
    <br>
    <input type="text" name="phone" placeholder="Телефон">
    <br>
    <textarea name="message" placeholder="Сообщение"></textarea>
    <br>
    <hr>
    <input type="submit" value="Отправить">
</form>
 <a href="#" onclick="history.back();" >Назад</a>
{% endblock %}

catalog/templates/catalog/item.html
{% extends 'catalog/base.html' %}


{% block content%}
{% load my_templatetags %}
<div class="col">
        <div class="card">
            <div class="card-body">
                <img src="{% mediapath object.img %}" alt="Изображение"  width="450" height="300"/>
                <table class="table">
                    <tr>
                        <td>Наименованиепродукта</td>
                        <td>{{ object.name }} </td>
                    </tr>
                    <tr>
                        <td>Описание продукта</td>
                        <td>{{ object.description }}</td>
                    </tr>
                    <tr>
                        <td>Категория</td>
                        <td>{{ object.category }}</td>
                    </tr>
                    <tr>
                        <td>Цена:</td>
                        <td>{{ object.price }} руб</td>
                    </tr>
                    <tr>
                        <td>Дата создания:</td>
                        <td>{{ object.date_of_creation }}</td>
                    </tr>
                    <tr>
                        <td>Дата последнего изменения:</td>
                            <td>{{ object.last_change_date }}</td>
                    </tr>
                </table>
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>


<a href="#" class="btn btn-primary" onclick="history.back();" >Назад</a>
{% endblock %}

catalog/templates/catalog/item_detail.html
{% extends 'catalog/base.html' %}


{% block content%}
<h1>Товар</h1>
{% load my_templatetags %}
<div class="col">
        <div class="card">
            <div class="card-body">
                <img src="{% mediapath object.img %}" alt="Изображение"  width="450" height="300"/>
                <table class="table">
                    <tr>
                        <td>Наименованиепродукта</td>
                        <td>{{ object.name }} </td>
                    </tr>
                    <tr>
                        <td>Описание продукта</td>
                        <td>{{ object.description }}</td>
                    </tr>
                    <tr>
                        <td>Категория</td>
                        <td>{{ object.category }}</td>
                    </tr>
                    <tr>
                        <td>Цена:</td>
                        <td>{{ object.price }} руб</td>
                    </tr>
                    <tr>
                        <td>Дата создания:</td>
                        <td>{{ object.date_of_creation }}</td>
                    </tr>
                    <tr>
                        <td>Дата последнего изменения:</td>
                            <td>{{ object.last_change_date }}</td>
                    </tr>
                </table>
            </div>
            <div class="card-footer">
                Просмотры: {{object.views_count}}
            </div>
        </div>
    </div>


<a href="#" class="btn btn-primary" onclick="history.back();" >Назад</a>
{% endblock %}

catalog/templates/catalog/product_by_category_list.html
{% extends 'catalog/base.html' %}
{% load my_templatetags %}

{% block content %}
<h1>Продукты выбранной категории</h1>

{% if user.is_authenticated %}
<div class="col-12 pb-md-4">

        <a class="btn btn-primary" href="{%url 'catalog:create_product'%}">Добавить продукт</a>

    </div>
{% endif%}

{% for object in object_list %}
<div class="col-6 text-center">
    <div class="card" style="width: 25rem;">
        <img src="{% mediapath object.photo %}" class="card-img-top" alt="">
        <div class="card-body">
            <a href="/item/{{ object.id }}" class="btn btn-primary"><h5 class="card-title">{{object.name}}</h5></a>
            <h4 class="card-title">{{object.price}} руб.</h4>
            <p class="card-text">{{object.description|truncatechars:100}}</p>
            <h6 class="card-text">{{object.photo}}</h6>
            {% for version in object.version_set.all %}
                {% if version.is_active %}
                    <p class="card-text">Версия: {{ version.version_name }} </p>
                    <p class="card-text">Номер версии: {{ version.version_number }} </p>
                {% endif %}
            {% endfor %}

        </div>

    </div>
</div>
{% endfor %}

<a href="#" class="btn btn-primary" onclick="history.back();" >Назад</a>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_templatetags %}

{% block content %}
<h1>Все продукты</h1>
    {% if user.is_authenticated %}
    <div class="col-12 pb-md-4">

            <a class="btn btn-primary" href="{%url 'catalog:create_product'%}">Добавить продукт</a>

        </div>
    {% endif %}
{% for object in object_list %}
{% if object.is_published == True %}
        <div class="col-6 text-center">
           <div class="card" style="width: 25rem;">
                <img src="{% mediapath object.photo %}" class="card-img-top" alt="">
                <div class="card-body">
                     <a href="/item/{{ object.id }}" class="btn btn-primary"><h5 class="card-title">{{object.name}}</h5></a>
                    <h4 class="card-title">{{object.price}} руб.</h4>
                    <p class="card-text">{{object.description|truncatechars:100}}</p>
                    <h6 class="card-text">{{object.photo}}</h6>
                    {% for version in object.version_set.all %}
                    {% if version.is_active %}
                    <p class="card-text">Версия: {{ version.version_name }} </p>
                    <p class="card-text">Номер версии: {{ version.version_number }} </p>
                </div>
                    {% endif %}
                    {% endfor %}
              <div class="btn-group m-4">
                    <a href="{% url 'catalog:item' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Просмотр</a>
                  {% if object.owner == user or user|has_group:'модератор' %}
                    <a href="{% url 'catalog:update_product' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Редактировать</a>
                  {% endif %}
                  {% if object.owner == user or user.is_superuser == True %}
                    <a href="{% url 'catalog:delete_product' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Удалить</a>
                  {% endif %}

            </div>
           </div>
        </div>
{% endif %}
{% endfor %}

{% endblock %}